# Generated by Django 2.2.19 on 2021-03-28 14:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_contentblock_video_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='block_image',
            field=models.ImageField(blank=True, null=True, upload_to='in_content_images/'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='oz_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='uz_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
