# Generated by Django 2.2.19 on 2021-03-28 16:31

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20210328_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='ru_content',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
