# Generated by Django 2.2.19 on 2021-03-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20210329_1819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentblock',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='updated_at',
        ),
    ]
