# Generated by Django 2.2.19 on 2021-04-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20210401_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='home_display',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='home_display',
            field=models.BooleanField(default=False),
        ),
    ]
