# Generated by Django 2.2.19 on 2021-04-06 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0016_article_view_count'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='tag',
            old_name='name',
            new_name='ru_name',
        ),
    ]
