# Generated by Django 2.2.19 on 2021-04-07 17:11

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0018_auto_20210407_0131'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статьи', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категории', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='contentblock',
            options={'ordering': ['id'], 'verbose_name': 'Блок', 'verbose_name_plural': 'Блоки'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'Подкатегории', 'verbose_name_plural': 'Подкатегории'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'Теги', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AlterField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='article',
            name='main_image',
            field=models.ImageField(upload_to='main_images/', verbose_name='Главное фото'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oz_heading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оглавление(на латинице)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='oz_subheading',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(на латинице)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ru_heading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оглавление(на русском)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='ru_subheading',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(на русском)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='sub_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.SubCategory', verbose_name='Подкатегория'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uz_heading',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Оглавление(на кирилице)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='uz_subheading',
            field=models.TextField(blank=True, null=True, verbose_name='Описание(на кирилице)'),
        ),
        migrations.AlterField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='Количество просмотров'),
        ),
        migrations.AlterField(
            model_name='category',
            name='oz_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название(на латинице)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='ru_name',
            field=models.CharField(max_length=20, verbose_name='Название(на русском)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uz_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название(на кирилице)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='block_image',
            field=models.ImageField(blank=True, null=True, upload_to='in_content_images/', verbose_name='Фото для блока'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='oz_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Блок (на латинице)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='ru_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Блок (на русском)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='uz_content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Блок (на кирилице)'),
        ),
        migrations.AlterField(
            model_name='contentblock',
            name='video_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ссылка для видео'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='oz_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название(на латинице)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='ru_name',
            field=models.CharField(max_length=20, verbose_name='Название(на русском)'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='uz_name',
            field=models.CharField(max_length=20, null=True, verbose_name='Название(на кирилице)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='oz_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Название(на латинице)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='ru_name',
            field=models.CharField(max_length=30, verbose_name='Название(на русском)'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='uz_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Название(на кирилице)'),
        ),
    ]
