# Generated by Django 2.2.19 on 2021-04-07 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='company_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
