# Generated by Django 2.2.19 on 2021-04-17 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_advertisement_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='link',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
