# Generated by Django 2.2.19 on 2021-04-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_advertisement_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
